### ISSUE TITLE
Suggestion: iOS notification when SRS kanji are due

### ISSUE THREAD

**Issue by MrFoote** [gbuela/kanjiryokucha#52]
Hi! Thanks for making this app, I was a bit confused about how it worked at first, but now I'm finding it very useful!

I was thinking it would be great to be notified in iOS when some kanji are due for flashcard review.

Keep up the good work!

**Comment by gbuela** [comment]
Hi MrFoote,
Thanks for the feedback. I would consider adding notifications that simply display a badge on the app's icon, no sound nor alerts, because they're probably too intrusive for this purpose. Also, I don't have control over the server which would take care of remote notifications, the badge would have to be set by a local notification. The app would schedule itself for polling the server a couple of times a day.
I haven't implemented a local notification before but if I find it technically feasible this may well be added on a future version.

**Comment by MrFoote** [comment]
Hi! I don't like intrusive apps, but I also appreciate if they give me an option. In the case of practicing kanji I kind of want it to be intrusive, because I want to be reminded to study. Or at least, I would like the option to be reminded.

I understand the scheduling / background polling problem... maybe too much to implement? But it would be a very nice feature!

Thanks

**Comment by gbuela** [comment]
I now have a build that implements background fetch that will update the badge, I will be testing it for a few days. No server side work needed.
Next I will look into adding (opt in)  alert notifications.

**Comment by gbuela** [comment]
I'm now going for the approach of opt-in notifications for both alerts and badge, because using just the badge still requires the permission request for notifications in the app. To avoid annoying users with this request up front, it will only trigger if they go to settings and enable notifications.

**Comment by MrFoote** [comment]
Sounds like a great solution! Thanks for considering my suggestion!

**Comment by gbuela** [comment]
Still trying to get this to work properly. Will leave the issue open until testing is finished.
